Repository KES-DASOM/MemoReal_App, pull requests merged in 2025-07, with the labels that each got.

#10 [fix] React 버전 수정
  package.json
  yarn.lock
Labels: 🐛 fix, 🐺 성환

#22 [chore] 메인페이지 타임캡슐 목록 BottomSheet로 구현
  App.tsx
  package.json
  src/components/UI/CapsuleBox.tsx
  src/components/layout/TimeCapsuleSheet.tsx
  src/screens/MainPage.tsx
  yarn.lock
Labels: 🐛 fix, 📦 chore, 🦊 수현

#23 [feat] 안드로이드 카카오 로그인 연동 및 로그인 UI 구현
  App.tsx
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/memoreal/MainActivity.kt
  android/app/src/main/res/values/strings.xml
  android/gradle.properties
  package.json
  src/assets/images/kakao_login_medium_narrow.png
  src/hooks/AuthContext.tsx
  src/navigation/AuthStackNavigator.tsx
  src/screens/LoginPage.tsx
  yarn.lock
Labels: 👾 feat, 😺 도현

#26 [feat] 타임캡슐 사진등록 기능 구현
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  package.json
  src/screens/CapsuleMainPage.tsx
  src/screens/CapsulePicturePage.tsx
  yarn.lock
Labels: 👾 feat, 🐨 세희

#29 [feat] 마이페이지 UI 구현
  package.json
  src/components/UI/CapsuleBox.tsx
  src/components/UI/MypageTabButton.tsx
  src/components/layout/MypageActionSection.tsx
  src/components/layout/MypageCapsuleList.tsx
  src/navigation/MyPageStackNavigator.tsx
  src/navigation/TabNavigator.tsx
  src/screens/MyPage.tsx
  src/screens/MyPageSettingPage.tsx
  src/store/types.ts
  src/store/useMypageTabStore.ts
  src/utils/cn.ts
  yarn.lock
Labels: 👾 feat, 🦊 수현

#33 [fix] 네비게이션 경로 수정 및 특정 페이지 비활성화
  src/navigation/CapsuleStackNavigator.tsx
  src/navigation/TabNavigator.tsx
  src/screens/CapsuleIndexPage.tsx
Labels: 🐛 fix, 📦 chore, 🦊 수현
